version = 0.1

[default.deploy.parameters]
stack_name = "sam-aws-service-recommender"
resolve_s3 = true
s3_prefix = "sam-aws-service-recommender"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
